### ISSUE TITLE
com.instagram.android Crash Report

### ISSUE THREAD

**Issue by michaelshadell25** [https-www-instagram-com-YmMyMTA2M2Y/mine#28]
USER_COMMENT=null
ANDROID_VERSION=13
APP_VERSION_NAME=263.2.0.19.104
BRAND=google
PHONE_MODEL=Pixel 6a
CUSTOM_DATA=
STACK_TRACE=java.lang.SecurityException: java uri "https://https//instagram.com/michaelshadell6/badge-it/api/v1/feed/timeline/" not equal to android uri "https://https://instagram.com/michaelshadell6/badge-it/api/v1/feed/timeline/". Debug info: javaUri authority: "https". androidUri authority: "https:".. Original uri: https://https://instagram.com/michaelshadell6/badge-it/api/v1/feed/timeline/
	at X.0Cz.A01(Unknown Source:397)
	at X.15M.A00(Unknown Source:328)
	at X.3N7.call(Unknown Source:7)
	at X.2Ya.run(Unknown Source:2)
	at X.19X.run(Unknown Source:2)
	at X.19e.run(Unknown Source:2)
	at X.2Wu.run(Unknown Source:26)
	at X.0k2.run(Unknown Source:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at X.0NO.run(Unknown Source:5)

**Comment by michaelshadell25** [comment]
> USER_COMMENT=null
> ANDROID_VERSION=13
> APP_VERSION_NAME=263.2.0.19.104
> BRAND=google
> PHONE_MODEL=Pixel 6a
> CUSTOM_DATA=
> STACK_TRACE=java.lang.SecurityException: java uri "https://https//instagram.com/michaelshadell6/badge-it/api/v1/feed/timeline/" not equal to android uri "https://https://instagram.com/michaelshadell6/badge-it/api/v1/feed/timeline/". Debug info: javaUri authority: "https". androidUri authority: "https:".. Original uri: https://https://instagram.com/michaelshadell6/badge-it/api/v1/feed/timeline/
> 	at X.0Cz.A01(Unknown Source:397)
> 	at X.15M.A00(Unknown Source:328)
> 	at X.3N7.call(Unknown Source:7)
> 	at X.2Ya.run(Unknown Source:2)
> 	at X.19X.run(Unknown Source:2)
> 	at X.19e.run(Unknown Source:2)
> 	at X.2Wu.run(Unknown Source:26)
> 	at X.0k2.run(Unknown Source:7)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
> 	at java.lang.Thread.run(Thread.java:1012)
> 	at X.0NO.run(Unknown Source:5)
> 
> 

@https-www-instagram-com-YmMyMTA2M2Y/bagde-it
